openapi: "3.0.2"
info:
  title: "AMP T2D Metadata API"
  description: "Metadata API for the project AMP-T2D"
  version: "1.0SNAPSHOT"
  termsOfService: "www.ebi.ac.uk/terms"
  contact:
    name: "Metadata API Admin"
    url: "www.ebi.ac.uk"
    email: "metadataapi@gmail.com"
  license:  
    name: "Apache 2.0"
    url: "https://www.apache.org/license/"
servers:
  - url: https://www.ebi.ac.uk/ega/ampt2d/metadata/1.0/
    description: Production server
paths:
  /publications:
    get:
      tags:
      - Publication Entity
      summary: "find all publications."
      description: "Get all publications of Type2Diabetes in AMP."
      operationId: GetPublicationEntity
      parameters:
      - name: page
        in: query
        description: "Number of pages."
        schema:
          type: string
      - name: size
        in: query
        description: "size of page."
        schema:
          type: string
      - name: sort
        in: query
        description: "Ascending or descending."
        schema:
          type: string
      responses:
        200:
          description: OK, Successful response
          content:
            application/json:
              schema:
                title: Model
                type: object
                properties:
                  lastModifiedDate:
                    type: string
                    description: lastModifiedDate of publication
                  id:
                    type: integer
                    description: unique id for publication generated
                  publicationId:
                    type: string
                    description: unique publication id submitted
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not found
    post:
      tags:
      - Publication Entity
      summary: "save publication."
      description: "Store a publication of Type2Diabetes in AMP."
      operationId: PostPublicationEntity
      requestBody:
        description: order placed for purchasing the pet
        content:
          'application/json':
            schema:
              title: Model
              type: object
              properties:
                publicationId:
                  type: string
                  description: unique id for publication
        required: true
      responses:
        200:
          description: OK, Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Publication'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not found
          
components:
  schemas:
    Publication:
      type: object
      properties:
        lastModifiedDate:
          type: string
          description: lastModifiedDate of publication
        id:
          type: integer
          description: unique id for publication generated
        publicationId:
          type: string
          description: unique publication id submitted
      xml:
        name: Order

  securitySchemes:
    keycloak_auth:
      type: oauth2
      flows:
        authorizationCode:
          tokenUrl:  http://localhost:8080/ega/ampt2d/auth/realms/securemetadata/protocol/openid-connect/token
          authorizationUrl: http://localhost:8080/ega/ampt2d/auth/realms/securemetadata/protocol/openid-connect/auth
          scopes:
            opened: openid

       
